### PR TITLE
Log show peak

### PR DESCRIPTION
**Pull request by BOPOHOP**
Fix to show peak annotation at log(y) mode

### CODE REVIEW

**Comment by NuclearPhoenixx** [comment]
Thanks. Just a reminder, #3 has to be merged before this PR, because it contains the same changes. Then review these changes again.

**Comment by ssesselmann** [comment]
Tested this improvement and added a little extra margin 👍

**Comment by ssesselmann** [comment]
annotations

**Review by ssesselmann — COMMENTED** [review]
All good works well, I increased margin slightly: "margin_t=40"

**Pull request merged**
