### PR TITLE
max finder based at parabolic approximation

### PR DESCRIPTION
**Pull request by BOPOHOP**
Replace max finder from simple max(samples) by max from parabola via sample[max-1],sample[max],sample[max+1]
Some optimization (height calculated only if pulse was properly positioned)

I know that pulse shape isn't parabolic, it depends of hardware,  typically they pretends to be "gaussian", but parabolic approximation seems to be better than "plain max".
In my case (pulse len=21 sample, not symmetric shape)  i got small resolution improvement (8.0% -> 7.7%) without extra cpu load. 
shape1

### CODE REVIEW

**Comment by ssesselmann** [comment]
Have you experimented with faster sample rate ?
newplot-5

**Comment by ssesselmann** [comment]
Arguably one might want to move the peak [max] to the right. Because the tail is far longer and may keep falling beyond the sample length.

newplot-6

**Comment by BOPOHOP** [comment]
> Have you experimented with faster sample rate ?
My hardware is 48KHz max, and  Raspberry PI don't want to resample audio stream...

**Comment by BOPOHOP** [comment]
> Arguably one might want to move the peak [max] to the right. Because the tail is far longer and may keep falling beyond the sample length.
Yes... One of my my PR is about peak position...

**Comment by ssesselmann** [comment]
Honestly I am not sure about this PR, it does not seem like good science to extrapolate a pulse height into the unknown. PRA solves this problem in a sligtly different way, it assumes that all pulses are by definition **under sampled**.  so it allows the user to apply a positive correction factor which is a function of pulse distortion. Meaning pulses with low distotion number get small correction and pulses with high distortion factor get more. Check out the PRA manual for the maths.

**Comment by ssesselmann** [comment]
Request closed

**Pull request closed without merging**
