### PR TITLE
GS-MAX/nano calibration from hardware; debug pulse shape decoding

### PR DESCRIPTION
**Pull request by BOPOHOP**
GS-MAX/nano is capable to hold calibration data, and AtomSpectra(andriod) or BqMon(win) can read/update calibration data (max polynom order up to 5)
Now impulse can read calibration data from hardware and build new order 2  polynom.
How to use: 
- select tab2
- push start
- select "read calibration" at "serial command"
- switch to other tab (tab3/tab1) and back to tab2 (don't touch other controls before tab switching)
- you can see updated calibration (and device serial number at json data)
Sorry I don't know how to update calibration bins/energies from callback so "strange" manual tab switching is required

basic decoding of output of pulse shape ("-mode 2")

### CODE REVIEW

**Comment by ssesselmann** [comment]
@BOBOHOP

Nice update, do you think there should also be an option to write 2nd. order calibration?

I need to look up how to refresh the page, it should also refresh page every time device is switched.

**Comment by BOPOHOP** [comment]
This code can be used to calculate AtomSpectra/BqMon compatible (calibration+checksum).
But i don't see how to  implement reliable  sequence of cal command  ("send -cal XX" wait for response then resend failed "-cal" error/timeout or sent next "-cal " ...) with current communication model.

from struct import *
import binascii


coeff = [ -3.50753, 0.369576, 8.31747E-06, -7.33575E-10, 0 ]

str = ''
r_n = 0
i = 0
c_b = [ pack('d', 0.) ] * 12
s = ''
for  v in coeff:
        c_b[i] = pack('d', coeff[i])
        vv = unpack('II', c_b[i])
        s += "%08X" % (vv[1])
        print("-cal {} {:08X}".format(r_n, vv[1]))
        s += "%08X" % (vv[0])
        r_n += 1
        print("-cal {} {:08X}".format(r_n, vv[0]))
        r_n += 1
        i += 1
crc = binascii.crc32(bytearray(s, "ascii")) % 2**32
print("-cal {} {:08X}".format(r_n, crc))

**Comment by ssesselmann** [comment]
I am happy to merge this request as is, we can look at the update calibration function to nono later

**Comment by ssesselmann** [comment]
Can you please explain the changes you made to dispatcher.py, I can't follow what you have done with the retrieved calibration data. 

I can see dispatcher gets 5 values for calibration[0], calibration[1] etc...

What are these 5 calibration points?

What are we doing with this value?

How are we updating the json file?

**Comment by ssesselmann** [comment]
Okay I found the problem and fixed the code, so calibration will work when changing the number of bins. 

Still have an issue with page refresh

**Comment by BOPOHOP** [comment]
> Can you please explain the changes you made to dispatcher.py, I can't follow what you have done with the retrieved calibration data.
> 
> I can see dispatcher gets 5 values for calibration[0], calibration[1] etc...
> 
> What are these 5 calibration points?

first 10 calibration registers (32bit) contains 5double coefficients of 5-order polynom (two registers per double value) + register for crc32(concatenated uppercase hex string for  cal0 ... cal10). This is strange checksum but this method already exists in AmtomSpectra and BqMon. They  assume that collected spectrum contains 8192 bins.
From "hardware point of view" calibration registers are generic storage and have no influence on collected spectra.

> What are we doing with this value?
> 
> How are we updating the json file?

The value in last calibration register is device serial number. This value added to  "deviceName". 
"deviceName":"GS-MAX or ATOM-NANO" is changed to  "GS-MAX or ATOM-NANO s/n: <<LAST_REG_VALUE>>"

**Pull request merged**
